# Generated by Django 4.2.3 on 2023-07-14 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('to_do_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
